version: "3.7"
services:
    postgres:
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRESS_PASSWORD
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
    api:
        build:
            context: .
            target: service
            args:
                - project=api-server
        restart: always
        secrets:
            - postgress_password
volumes:
    postgres_data:
secrets:
  postgress_password:
    external: true
